site_name: The Midnight Wiki
docs_dir: 'docs'
site_dir: 'site'

theme: readthedocs

markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Frequently Asked Questions: faq.md
    - Rewrite Information: rewrite.md
    - About:
        - What is The Midnight?: about.md
        - Credits: about/credits.md