modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Cryptic-Mushroom/The-Midnight/issues"

[[mods]]
modId="midnight"
version="${file.jarVersion}"
displayName="The Midnight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-midnight"
updateJSONURL="https://raw.githubusercontent.com/Cryptic-Mushroom/The-Midnight/old/1.15.2/changelog.json"
logoFile="logo.png"
#credits="Cipher Zero X, RedGalaxySW, Jonathing, bagu_chan, gegy1000, Corail31, Lachney, Five (Paradiscal), Martacus, Cat Core, Endergized, MCVinnyq"
authors="The Midnight Development Team from Cryptic Mushroom"
description='''
The Midnight is a mod being developed by Cryptic Mushroom that adds a new, mysterious and scary dimension to explore. It is a dimension of darkness; the only light comes from crystals and the various life of the dimension. You may travel willingly to this dimension, though you may unwillingly encounter a rifter and be dragged into this strange and hostile world...

This mod is a huge collaborative effort with tons of different ideas, coding, and textures pitched in by varying individuals who came together to build something great. We wouldn't be where we are today without the help of those here today and those who worked on this mod in the past.

The Midnight Development Team Active Developers
Cipher Zero X - Project Lead, Mastermind, Modeler
RedGalaxySW - Lead Programmer
Jonathing - Lead QA, Community Manager, Programmer, Musician
Lachney - Lead Sound Designer, Lead Musician
123wdog - Lead Modeler

Former and Inactive Developers
bagu_chan - Programmer
gegy1000 - Programmer
Martacus - Programmer
arthurbambous - Programmer
Corail31 - Programmer
Endergized - Texturer
Five (Paradiscal) - Texturer
MCVinnyq - Texturer, Modeler

We are currently rewriting The Midnight from the ground up and we'd love to hear your feedback on this version so we know what to keep track of when writing the new version! You can join our Discord server from the CurseForge page for more information.
'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
