modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Cryptic-Mushroom/The-Midnight/issues"

[[mods]]
modId="midnight"
version="${file.jarVersion}"
displayName="The Midnight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-midnight"
#updateJSONURL=""
logoFile="logo.png"
credits="Special thanks to all past authors and contributors!"
authors="Cipher Zero X, RedGalaxySW, Jonathing, bagu_chan, gegy1000, Corail31, Lachney, Five (Paradiscal), Martacus, Cat Core, Endergized, MCVinnyq"
description='''
The Midnight adds a brand new dimension to explore full of unique adventures and dangers!
It's a dimension of perpetual darkness; the only light comes from crystals and the various flora and fauna of the dimension.
You may travel willingly to this dimension, though you may unwillingly be dragged by a Rifter into this strange, hostile world...
'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
