modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Cryptic-Mushroom/The-Midnight/issues"

[[mods]]
modId="midnight"
version="${file.jarVersion}"
displayName="The Midnight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-midnight"
#updateJSONURL=""
logoFile="logo.png"
credits=""
authors="cipherzerox, bagu_chan, RedGalaxySW, Jonathing, Endergized, Lachney, Gegy, Corail31, Martacus"
description='''
The Midnight adds a brand new dimension to explore full of unique adventures and dangers!
It's a dimension of perpetual darkness; the only light comes from crystals and the various flora and fauna of the dimension.
You may travel willingly to this dimension, though you may unwillingly be dragged by a Rifter into this strange, hostile world...
'''

[[dependencies.midnight]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.midnight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
