blank_issues_enabled: true
contact_links:
  - name: Feature Request 🚀
    url: https://github.com/Cryptic-Mushroom/The-Midnight/discussions
    about: Request a feature/enhancement to The Midnight. (1.12.2 and 1.14.4 not supported)
