# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: The Midnight for Minecraft 1.16.1

on:
  push:
    branches:
      - 1.16.1
    paths-ignore:
      - '.github/**'
      - 'curseforge/**'
      - 'README.md'
      - 'LICENSE'
      - 'changelog.json'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update CI Workspace
      uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64

    - name: Build The Midnight for Minecraft 1.16.1
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 4.10.3
        arguments: build

    - name: Upload The Midnight API to GitHub
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: midnight-api-${{ github.sha }}
        # A file, directory or wildcard pattern that describes what to upload
        path: MidnightAPI/build/libs/*.jar

    - name: Upload The Midnight Core to GitHub
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: midnight-core-${{ github.sha }}
        # A file, directory or wildcard pattern that describes what to upload
        path: MidnightCore/build/libs/*.jar

    - name: Upload The Midnight to GitHub
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: midnight-mod-${{ github.sha }}
        # A file, directory or wildcard pattern that describes what to upload
        path: MidnightMod/build/libs/*.jar