# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

# @Jonathing or anyone who knows CI please have a look at this

name: The Midnight (Fabric)

on:
  push:
    branches:
      - fabric/rewrite
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'curseforge/**'
      - 'versioninfo/**'
      - 'README.md'
      - 'LICENSE.md'
      - 'GRADLE.md'
      - 'changelog.json'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'
  schedule:
    - cron: '0 12 * * 2,6'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Update CI Workspace
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
          architecture: x64

      - name: Prepare to build The Midnight
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo ""
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          git clone git@github.com:${{ secrets.PRIVATE_REPO }}
          echo "" >> gradle.properties
          echo "mnKeyStore=${{ secrets.JKS_NAME }}" >> gradle.properties
          echo "mnKeyStoreAlias=${{ secrets.JKS_ALIAS }}" >> gradle.properties
          echo "mnKeyStorePass=${{ secrets.JKS_PASS }}" >> gradle.properties
          echo "mnKeyStoreKeyPass=${{ secrets.JKS_PASS }}" >> gradle.properties
          echo "mnKeyStoreSHA256=${{ secrets.JKS_SHA256 }}" >> gradle.properties
          cp ${{ secrets.PRIVATE_REPO_NAME }}/${{ secrets.JKS_NAME }} ./${{ secrets.JKS_NAME }}
          rm -rf ${{ secrets.PRIVATE_REPO_NAME }}
          echo "Ready to build and sign The Midnight."

      - name: Retrieve any cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-fabric-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
           ${{ runner.os }}-gradle-

      - name: Build The Midnight
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.7
          arguments: build -x genData --no-daemon
          
      - name: Prepare to upload the build outputs
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "Ready to upload the build output to GitHub."
          
      - name: Upload The Midnight to GitHub
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: midnight-fabric-universal-${{ env.SHORT_SHA }}
          # A file, directory or wildcard pattern that describes what to upload
          path: build/libs/***+fabric.jar
