# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: The Midnight (Pre-Rewrite)

on:
  push:
    branches:
      - old/1.15.2
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Update CI Workspace
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64

    - name: Retrieve any cached dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-preRewrite-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-preRewrite-

    - name: Build The Midnight
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 4.10.3
        arguments: build --no-daemon

    - name: Prepare to upload the build outputs
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
        echo "Ready to upload the build output to GitHub."

    - name: Upload The Midnight to GitHub
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: midnight-universal-${{ env.SHORT_SHA }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
